import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { join } from 'path';
import { existsSync, unlinkSync } from 'fs';

describe('Roo Code Integration', () => {
    let client: Client;
    let transport: StdioClientTransport;
    const testFile = join(process.cwd(), 'temp_roo_test.ts');

    beforeEach(async () => {
        // Start the MCP server as a subprocess
        transport = new StdioClientTransport({
            command: 'npx',
            args: ['tsx', 'src/mcp_servers/roo_code/index.ts']
        });

        client = new Client({
            name: "test-client",
            version: "1.0.0",
        }, {
            capabilities: {}
        });

        await client.connect(transport);
    });

    afterEach(async () => {
        await transport.close();
        if (existsSync(testFile)) {
            // unlinkSync(testFile);
        }
    });

    it('should discover roo_code tools', async () => {
        const tools = await client.listTools();
        const toolNames = tools.tools.map(t => t.name);
        expect(toolNames).toContain('execute_task');
        expect(toolNames).toContain('roo_review_code');
        expect(toolNames).toContain('roo_fix_code');
        expect(toolNames).toContain('roo_generate_docs');
    });

    it('should execute execute_task', async () => {
        const result = await client.callTool({
            name: 'execute_task',
            arguments: { task: 'Optimize database queries', session_id: 'test-session' }
        });
        const output = result.content[0].text;
        expect(output).toContain('Task Execution Result');
        expect(output).toContain('success');
    });

    it('should execute roo_review_code', async () => {
        const result = await client.callTool({
            name: 'roo_review_code',
            arguments: { file_path: 'src/utils.ts' }
        });

        const output = result.content[0].text;
        expect(output).toContain('Roo Code Analysis for src/utils.ts');
        expect(output).toContain('Complexity');
    });

    it('should execute roo_fix_code', async () => {
        const result = await client.callTool({
            name: 'roo_fix_code',
            arguments: { file_path: 'src/utils.ts', strategy: 'aggressive' }
        });

        const output = result.content[0].text;
        expect(output).toContain('Roo Code Fix Applied');
        expect(output).toContain('success');
    });

    it('should execute roo_generate_docs', async () => {
        const result = await client.callTool({
            name: 'roo_generate_docs',
            arguments: { file_path: 'src/utils.ts' }
        });

        const output = result.content[0].text;
        expect(output).toContain('Documentation for src/utils.ts');
        expect(output).toContain('Generated by Roo Code');
    });
});
