#!/bin/bash

# Simple CLI - Quick Start Production Script
# Automates the setup for a production deployment.

set -e

APP_DIR="/opt/simple-agent"
DATA_DIR="$APP_DIR/data"
ENV_FILE="$APP_DIR/.env"

echo "🚀 Starting Simple CLI Production Setup..."

# 1. Check Prerequisites
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi

# 2. Create Directory Structure
echo "📂 Creating directory structure at $APP_DIR..."
sudo mkdir -p "$DATA_DIR/brain"
sudo mkdir -p "$DATA_DIR/companies"
sudo mkdir -p "$DATA_DIR/logs"

# 3. Create .env file if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    echo "🔑 Generating .env file..."
    sudo touch "$ENV_FILE"
    sudo chmod 600 "$ENV_FILE"

    cat <<EOF | sudo tee "$ENV_FILE" > /dev/null
# Generated by quick_start_production.sh
NODE_ENV=production

# LLM Keys
OPENAI_API_KEY=your_openai_key_here
ANTHROPIC_API_KEY=your_anthropic_key_here

# Slack Integration
SLACK_BOT_TOKEN=xoxb-placeholder
SLACK_APP_TOKEN=xapp-placeholder
SLACK_SIGNING_SECRET=secret-placeholder

# Teams Integration (Optional)
# MicrosoftAppId=
# MicrosoftAppPassword=

# Database URLs (if using external)
REDIS_URL=redis://redis:6379
POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/postgres
EOF
    echo "✅ .env created at $ENV_FILE. Please edit it with your real keys!"
else
    echo "ℹ️  .env file already exists. Skipping generation."
fi

# 4. Copy docker-compose.yml (Assumes script is run from repo root or file is available)
# If run standalone, you might curl it. Here we assume repo context.
if [ -f "docker-compose.yml" ]; then
    echo "📦 Copying docker-compose.yml..."
    sudo cp docker-compose.yml "$APP_DIR/"
else
    echo "⚠️  docker-compose.yml not found in current directory. Downloading default..."
    # Placeholder for download logic if needed, or just warn.
    # For now, we'll write a basic one.
    cat <<EOF | sudo tee "$APP_DIR/docker-compose.yml" > /dev/null
services:
  agent:
    image: ghcr.io/your-org/simple-cli:latest
    container_name: simple-agent
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data/brain:/app/.agent/brain
      - ./data/companies:/app/.agent/companies
      - ./data/logs:/app/.agent/logs
      - ./mcp.json:/app/mcp.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
EOF
fi

# 5. Set Permissions
echo "🔒 Setting permissions..."
sudo chown -R 1000:1000 "$DATA_DIR" # Assuming node user is 1000

echo "✅ Setup Complete!"
echo "------------------------------------------------"
echo "Next Steps:"
echo "1. Edit $ENV_FILE with your API keys."
echo "2. Run 'cd $APP_DIR && sudo docker-compose up -d'"
echo "3. Monitor logs with 'sudo docker logs -f simple-agent'"
echo "------------------------------------------------"
